/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Iiitg.java
 *
 * Created on Feb 9, 2019, 1:17:34 AM
 */

/**
 *
 * @author MP
 */
public class Iiitg extends javax.swing.JFrame {

    /** Creates new form Iiitg */
    public Iiitg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 550));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 440, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iiitg.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 830, 160);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iiitginfo.JPG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 310, 690, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 123);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 848, 521);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Jossa n2=new Jossa();
        n2.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iiitg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
