/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Jossa.java
 *
 * Created on Feb 9, 2019, 12:15:48 AM
 */

/**
 *
 * @author MP
 */
public class Jossa extends javax.swing.JFrame {

    /** Creates new form Jossa */
    public Jossa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("1.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 210, 30, 17);

        jLabel12.setText("Indian Institute of Information");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 200, 150, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 150, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 150, 120, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("3.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 370, 30, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("99360 01883");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 210, 100, 17);

        jLabel13.setText("Technology,Allahabad");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 220, 150, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View Details");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 150, 120, 22);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 210, 70, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("91913 63322");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(330, 450, 90, 17);

        jLabel18.setText("adean.aaa@iiita.ac.in");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(450, 210, 140, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("87772 77821");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(330, 370, 90, 17);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 280, 70, 23);

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 440, 70, 23);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View");
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 360, 70, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("4.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 450, 30, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("76355 77532");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 290, 100, 17);

        jLabel21.setText("Indian Institute of Information");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(120, 280, 270, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("2.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 290, 30, 17);

        jLabel22.setText(" Technology ,Guwahati");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(120, 294, 130, 20);

        jLabel20.setText("admissions@iiitg.ac.in");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(450, 290, 140, 20);

        jLabel23.setText("Indian Institute of Information");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(120, 350, 170, 14);

        jLabel26.setText("Technology ,Pune\t");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(120, 460, 130, 14);

        jLabel25.setText("Indian Institute of Information");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(120, 440, 170, 14);

        jLabel24.setText(" Technology,Nagpur");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(120, 370, 140, 14);

        jLabel28.setText("kndakhale@vnit.ac.in");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(450, 370, 130, 14);

        jLabel29.setText("ssp.mech@coep.ac.in");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(450, 450, 130, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Institute Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 150, 160, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S.No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 60, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 130, 700, 365);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.JPG"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(-20, 0, 1060, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -30, 848, 560);

        jLabel27.setText("jLabel27");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(680, 250, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Iiita n2=new Iiita();
        n2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Iiitg n2=new Iiitg();
        n2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jossa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
